### ISSUE TITLE
TypeError: Cannot read property '_vm' of undefined

### ISSUE THREAD

**Issue by wighawag** [ethereum-optimism/smock#3]
Hi, smock is great.

 found an issue :

When I run my test via https://github.com/cgewecke/eth-gas-reporter/ I get the following error:

```
     TypeError: Cannot read property '_vm' of undefined
      at exports.smoddit (node_modules\@eth-optimism\smock\src\smoddit\smoddit.ts:30:49)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I think the issue is that this code is not sufficient as provider["_wrapped"]["_wrapped"]... can go for longer.
https://github.com/ethereum-optimism/smock/blob/f1ce45818a9c9f2f1dee46b3560a57320537a514/src/smoddit/smoddit.ts#L27

Also I am just wondering if you got in touch with hardhat team

this line access the internal of hardhat : https://github.com/ethereum-optimism/smock/blob/f1ce45818a9c9f2f1dee46b3560a57320537a514/src/smoddit/smoddit.ts#L30

@alcuadrado maybe, hardhat should expose the vm via an API ?

This would remove the need for ["_wrapper"] thing

**Comment by alcuadrado** [comment]
There's an experimental api that lets you hook your plugin into the execution traces of txs and calls. It's not documented yet, but solidity-coverage uses it.

**Comment by smartcontracts** [comment]
@wighawag thanks for reporting this. I think you're correct about the source of the issue. I'm going to push this to the next version of smock since I have some pretty heavy rewrites coming in.

**Comment by smartcontracts** [comment]
Smock `1.0.0-alpha.1` should no longer have this issue! I'm looking for a few people to beta test it, would greatly appreciate if you have a few minutes to try it out! :-)

**Comment by wighawag** [comment]
getting this error after upgrading to 1.0.0-alpha.1

```
Error: Cannot find module 'C:\dev\thesandboxgame\sandbox-smart-contracts\node_modules\@eth-optimism\smock\build\src\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\dev\thesandboxgame\sandbox-smart-contracts\test\liquidityMining\smockSANDRewardPool.test.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\dev\\thesandboxgame\\sandbox-smart-contracts\\node_modules\\@eth-optimism\\smock\\package.json',
  requestPath: '@eth-optimism/smock'

**Comment by smartcontracts** [comment]
Whoops. Pushing out a fix in #29.
